# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: offload_proto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='offload_proto.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\022com.example.accumo',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13offload_proto.proto\"\x88\x01\n\x0eUploadMetadata\x12\x10\n\x08\x66rameIdx\x18\x01 \x01(\x05\x12\x11\n\tframeSize\x18\x02 \x01(\x05\x12\x10\n\x08taskType\x18\x03 \x01(\x05\x12\x0c\n\x04imgH\x18\x04 \x01(\x05\x12\x0c\n\x04imgW\x18\x05 \x01(\x05\x12\x10\n\x08\x64istance\x18\x06 \x01(\x01\x12\x11\n\tyuvFormat\x18\x07 \x01(\t\"\xab\x01\n\x10\x44ownloadMetadata\x12\x10\n\x08\x66rameIdx\x18\x01 \x01(\x05\x12\x12\n\nresultSize\x18\x02 \x01(\x05\x12\x10\n\x08taskType\x18\x03 \x01(\x05\x12\x17\n\x0ftask0ResultSize\x18\x04 \x01(\x05\x12\x14\n\x0ctimeDecoding\x18\x05 \x01(\x03\x12\x15\n\rtimeInference\x18\x06 \x01(\x03\x12\x19\n\x11readDepthFromDisk\x18\x07 \x01(\x08\x42\x14\n\x12\x63om.example.accumob\x06proto3'
)




_UPLOADMETADATA = _descriptor.Descriptor(
  name='UploadMetadata',
  full_name='UploadMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frameIdx', full_name='UploadMetadata.frameIdx', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frameSize', full_name='UploadMetadata.frameSize', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='taskType', full_name='UploadMetadata.taskType', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imgH', full_name='UploadMetadata.imgH', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imgW', full_name='UploadMetadata.imgW', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='distance', full_name='UploadMetadata.distance', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='yuvFormat', full_name='UploadMetadata.yuvFormat', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=160,
)


_DOWNLOADMETADATA = _descriptor.Descriptor(
  name='DownloadMetadata',
  full_name='DownloadMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frameIdx', full_name='DownloadMetadata.frameIdx', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resultSize', full_name='DownloadMetadata.resultSize', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='taskType', full_name='DownloadMetadata.taskType', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='task0ResultSize', full_name='DownloadMetadata.task0ResultSize', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timeDecoding', full_name='DownloadMetadata.timeDecoding', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timeInference', full_name='DownloadMetadata.timeInference', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='readDepthFromDisk', full_name='DownloadMetadata.readDepthFromDisk', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=334,
)

DESCRIPTOR.message_types_by_name['UploadMetadata'] = _UPLOADMETADATA
DESCRIPTOR.message_types_by_name['DownloadMetadata'] = _DOWNLOADMETADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UploadMetadata = _reflection.GeneratedProtocolMessageType('UploadMetadata', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADMETADATA,
  '__module__' : 'offload_proto_pb2'
  # @@protoc_insertion_point(class_scope:UploadMetadata)
  })
_sym_db.RegisterMessage(UploadMetadata)

DownloadMetadata = _reflection.GeneratedProtocolMessageType('DownloadMetadata', (_message.Message,), {
  'DESCRIPTOR' : _DOWNLOADMETADATA,
  '__module__' : 'offload_proto_pb2'
  # @@protoc_insertion_point(class_scope:DownloadMetadata)
  })
_sym_db.RegisterMessage(DownloadMetadata)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
